// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_actions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAction = `-- name: CreateUserAction :one
INSERT INTO user_actions (
    user_id,
    action
) VALUES (
    $1, $2
)
RETURNING id, created_at, updated_at, user_id, action
`

type CreateUserActionParams struct {
	UserID pgtype.UUID
	Action UserActionType
}

func (q *Queries) CreateUserAction(ctx context.Context, arg CreateUserActionParams) (UserAction, error) {
	row := q.db.QueryRow(ctx, createUserAction, arg.UserID, arg.Action)
	var i UserAction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Action,
	)
	return i, err
}
